# SPDX-License-Identifier: GPL-2.0
#
# drivers/vxtux/thermal/Makefile — LinDroid/VXTux v1.0

obj-$(CONFIG_VXTUX_SPRD_GPU_COOLING)	+= sprd_gpu_cooling.o
obj-$(CONFIG_SPRD_TSENSOR_THERMAL)	+= sc27xx_tsensor_thermal.o
obj-$(CONFIG_SPRD_SOC_THM)	+= sprd_soc_thm.o
obj-$(CONFIG_SPRD_CPU_COOLING)	+= sprd_cpu_cooling.o
