# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_SPRD_VSP_PW_DOMAIN) += sprd_vsp_pw_domain.o
obj-$(CONFIG_SPRD_CAMSYS_PW_DOMAIN) += sprd_camsys_pw_domain.o
obj-$(CONFIG_SPRD_GPU_PW_DOMAIN) += sprd_gpu_pw_domain.o
obj-$(CONFIG_SPRD_VSP_PW_DOMAIN) += vsp_regs.o