# SPDX-License-Identifier: GPL-2.0
#
# media/platform/sprd/pipeline/Makefile — Unisoc CSI/ISP pipeline glue.

obj-$(CONFIG_MEDIA_SPRD_PIPELINE) += sprd_dcam.o
obj-$(CONFIG_MEDIA_SPRD_PIPELINE) += sprd_csi.o
obj-$(CONFIG_MEDIA_SPRD_PIPELINE) += sprd_mipi_csi_phy.o
obj-$(CONFIG_MEDIA_SPRD_PIPELINE) += sprd_isp.o
