# SPRD voice trigger shim node (blob: voice_trigger)
# Port 2026-10-04 from gpl-source/fork_t618/.../drivers/misc/sprd_audio/voice_trigger/
obj-$(CONFIG_SPRD_AUDIO_VOICE_TRIGGER) += voice_trigger_node.o
ccflags-y += -I$(srctree)/drivers/sound/soc/sprd/include
