# SPDX-License-Identifier: GPL-2.0
# drivers/vxtux/soc/Makefile
obj-$(CONFIG_SPRD_USBPINMUX)	+= usbpinmux/
obj-$(CONFIG_SPRD_PMIC_SYSCON)	+= pmic_syscon/
obj-$(CONFIG_SPRD_SOCID)	+= soc_id/
obj-$(CONFIG_SPRD_HWFEATURE)	+= hwfeature/
obj-$(CONFIG_NVMEM_SPRD_CACHE_EFUSE) += cache_efuse/
obj-$(CONFIG_SPRD_POWER_MANAGER) += power_manager/
