# SPRD audio pipe (blob: audio_pipe)
# Port 2026-10-04 from gpl-source/fork_t618/.../drivers/misc/sprd_audio/audio_pipe/
obj-y += audio_pipe.o
ccflags-y += -I$(srctree)/drivers/sound/soc/sprd/include
