// SPDX-License-Identifier: GPL-2.0
/*
 * sprd_usbpinmux.c — Unisoc USB pinmux (D+ / UART-JTAG mux), port 5.4 -> 6.18.
 *
 * GPL source: fork Samsung Tab A8 (T618/UMS512)
 *   drivers/soc/sprd/usbpinmux/sprd_usbpinmux_qogirl6.c
 *
 * 6.18 adaptation (verified in tree, not guessed):
 *   - syscon_get_args_by_name() NOT PRESENT in 6.18 -> of_property_read_u32_array()
 *     on property <name> = <reg mask> on own node (identical behavior).
 *   - remove() must be void (platform_device.h:238).
 *   - additional compatibles sharkl5pro/sharkl5 (our SoC) — generic driver logic.
 *
 * Function: if USBMux mux is open (not JTAG/APWDG), raise usbmux VDD and
 * select pinctrl state uart_inf_sel0/sel1 so D+/D- use USB path, not JTAG.
 */
#include <linux/delay.h>
#include <linux/err.h>
#include <linux/errno.h>
#include <linux/export.h>
#include <linux/init.h>
#include <linux/io.h>
#include <linux/mfd/syscon.h>
#include <linux/module.h>
#include <linux/of.h>
#include <linux/platform_device.h>
#include <linux/pinctrl/consumer.h>
#include <linux/regmap.h>
#include <linux/regulator/consumer.h>

#define DRV_NAME	"sprd-usbpinmux"

/* mux value meaning "USBMux closed" (JTAG/APWDG holds pin) */
#define JTAG_APWDG_VAL	0x1

static struct regmap	*usbmux_cfg;
static u32		usb_uart_jtag_mux_reg;
static u32		usb_uart_jtag_mux_mask;

/* Used by other USB/charger drivers (fork: sprd_usbmux_check_mode). */
/* provider declaration (generated by tools/re/fix_provider_proto.py; fixes -Wmissing-prototypes) */
int sprd_usbmux_check_mode(void);
int sprd_usbmux_check_mode(void)
{
	u32 mux_val;
	int ret;

	if (!usbmux_cfg)
		return -EINVAL;

	ret = regmap_read(usbmux_cfg, usb_uart_jtag_mux_reg, &mux_val);
	if (ret) {
		pr_err("Failed to read mux_val\n");
		return -EINVAL;
	}

	if (mux_val && mux_val != JTAG_APWDG_VAL) {
		pr_debug("USBMux open: mux_val = 0x%x\n", mux_val);
		return 1;
	}

	return 0;
}
EXPORT_SYMBOL_GPL(sprd_usbmux_check_mode);

/* replacement for syscon_get_args_by_name(): property <name> = <reg> <mask> */
static int usbmux_get_args(struct device *dev, const char *name,
			   u32 *args, int nargs)
{
	int n;

	n = of_property_count_u32_elems(dev->of_node, name);
	if (n != nargs) {
		dev_dbg(dev, "%s: property not found/wrong arguments (%d)\n",
			name, n);
		return -EINVAL;
	}

	return of_property_read_u32_array(dev->of_node, name, args, nargs);
}

static int sprd_usbpinmux_probe(struct platform_device *pdev)
{
	struct device *dev = &pdev->dev;
	struct pinctrl *uart_ctrl;
	struct pinctrl_state *uctrl_state0, *uctrl_state1;
	struct regulator *vdd_on;
	u32 args[2], vdd_vol;
	int ret;

	usbmux_cfg = syscon_regmap_lookup_by_phandle(dev->of_node,
						     "sprd,syscon-config");
	if (IS_ERR(usbmux_cfg)) {
		dev_err(dev, "ap usbmux_cfg syscon failed!\n");
		return PTR_ERR(usbmux_cfg);
	}

	ret = usbmux_get_args(dev, "usb_uart_jtag_mux", args, 2);
	if (!ret) {
		usb_uart_jtag_mux_reg = args[0];
		usb_uart_jtag_mux_mask = args[1];
		dev_dbg(dev, "usb_uart_jtag_mux: reg:%x mask:%x\n",
			args[0], args[1]);
	} else {
		dev_warn(dev, "usb_uart_jtag_mux not readable — mux assumed closed\n");
		return 0;
	}

	if (sprd_usbmux_check_mode() <= 0)
		return 0;	/* JTAG/APWDG holds pin — don't touch */

	ret = of_property_read_u32(dev->of_node, "sprd,vdd-voltage", &vdd_vol);
	if (ret < 0) {
		dev_err(dev, "unable to read usbmux vdd voltage\n");
		return ret;
	}

	vdd_on = devm_regulator_get(dev, "vdd");
	if (IS_ERR(vdd_on)) {
		dev_err(dev, "unable to get usbmux vdd supply\n");
		return PTR_ERR(vdd_on);
	}

	ret = regulator_set_voltage(vdd_on, vdd_vol, vdd_vol);
	if (ret < 0) {
		dev_err(dev, "fail to set usbmux vdd voltage at %dmV\n", vdd_vol);
		return ret;
	}

	ret = regulator_enable(vdd_on);
	if (ret) {
		dev_err(dev, "fail to enable regulator!\n");
		return ret;
	}

	uart_ctrl = devm_pinctrl_get(dev);
	if (IS_ERR(uart_ctrl)) {
		dev_err(dev, "ERR:get pinctrl failed\n");
		return -ENODEV;
	}

	uctrl_state0 = pinctrl_lookup_state(uart_ctrl, "uart_inf_sel0");
	if (IS_ERR(uctrl_state0)) {
		dev_err(dev, "pinctrl lookup uart_inf_sel0 failed!\n");
		return PTR_ERR(uctrl_state0);
	}

	uctrl_state1 = pinctrl_lookup_state(uart_ctrl, "uart_inf_sel1");
	if (IS_ERR(uctrl_state1)) {
		dev_err(dev, "pinctrl lookup uart_inf_sel1 failed!\n");
		return PTR_ERR(uctrl_state1);
	}

	ret = pinctrl_select_state(uart_ctrl, uctrl_state0);
	if (ret) {
		dev_err(dev, "pinctrl_sel_state uart_inf_sel0 failed!\n");
		return ret;
	}

	ret = pinctrl_select_state(uart_ctrl, uctrl_state1);
	if (ret) {
		dev_err(dev, "pinctrl_sel_state uart_inf_sel1 failed!\n");
		return ret;
	}

	dev_info(dev, "USBMux open: vdd=%umV, UART->USB pin selected\n", vdd_vol);
	return 0;
}

static void sprd_usbpinmux_remove(struct platform_device *pdev)
{
	usbmux_cfg = NULL;
}

static const struct of_device_id sprd_usbpinmux_of_match[] = {
	{ .compatible = "sprd,sharkl5pro-usbpinmux" },
	{ .compatible = "sprd,sharkl5-usbpinmux" },
	{ .compatible = "sprd,qogirl6-usbpinmux" },
	{ /* sentinel */ }
};
MODULE_DEVICE_TABLE(of, sprd_usbpinmux_of_match);

static struct platform_driver sprd_usbpinmux_driver = {
	.probe = sprd_usbpinmux_probe,
	.remove = sprd_usbpinmux_remove,
	.driver = {
		.name = DRV_NAME,
		.of_match_table = sprd_usbpinmux_of_match,
	},
};
module_platform_driver(sprd_usbpinmux_driver);

MODULE_LICENSE("GPL v2");
MODULE_AUTHOR("Porter Xu <porter.xu@unisoc.com> (fork GPL)");
MODULE_AUTHOR("LinDroid/VXTux — port 6.18");
MODULE_DESCRIPTION("Unisoc platform USB pinmux driver (VXTux port)");
