# SPRD CP dump -- /dev/cp_dump, also used by modem_control.
# Port 2026-10-04 from gpl-source/fork_t618/extract/soc/drivers/soc/sprd/modem/cp_dump/
obj-$(CONFIG_SPRD_CP_DUMP) += sprd_cp_dump.o

ccflags-y += -I$(srctree)/drivers/soc/sprd/modem/include
ccflags-y += -I$(srctree)/drivers/soc/sprd/modem/include
