# SPRD camera flash HAL (blob: sprd_flash_drv)
# Port 2026-10-04 from work/donorcatalog/mods-sprd/sprd/common/camera/flash/flash_drv/
obj-$(CONFIG_SPRD_FLASH_DRV) += flash_drv.o
ccflags-y += -I$(src)
