# Spreadtrum saudio (blob: saudio)
# Port 2026-10-04 from gpl-source/fork_t618/.../drivers/misc/sprd_audio/saudio/
obj-$(CONFIG_SPRD_AUDIO_SAUDIO) += saudio.o
ccflags-y += -I$(srctree)/drivers/sound/soc/sprd/include
